### ISSUE TITLE
[Bug]User is logged out on page reload after login

### ISSUE THREAD

**Issue by karankoder** [leocodeio/StarClassifier#11]
Currently, users are automatically logged out on page reload, which disrupts the user experience. This issue aims to implement session persistence using cookies so that users remain logged in until they explicitly log out or the session expires.

Please assign this issue to me for implementation.

**Comment by leocodeio** [comment]
@karankoder  way to go..

**Comment by karankoder** [comment]
@leocodeio can i remove "remember me" option from login and registration form?
As there will be no use of it, after cookie authentication.

**Comment by leocodeio** [comment]
@karankoder nope i should be look about it later at the time of session creation or some logic that i would look into in future

**Comment by karankoder** [comment]
@leocodeio i have created a PR for this issue, please review.

**Comment by leocodeio** [comment]
@karankoder  great work out there, just merged your pr thanks for contributing
