### ISSUE TITLE
[FEAT] Alerts ,Error and confirmation messages at time of signup 

### ISSUE THREAD

**Issue by leocodeio** [leocodeio/StarClassifier#8]
1. should be able to handle the success or failures at the time of login or sign up 
2. And show a 4 sec pop up showing the message of cause
<img src="https://github.com/user-attachments/assets/d4c75058-b3a4-4f65-b979-ca543739556a" alt="description" width="400">

3. it should be appearing at right corner
<img src="https://github.com/user-attachments/assets/85d19ed8-f413-4110-8b29-bf3cf779ad87" alt="description" width="400">

**Comment by karankoder** [comment]
@leocodeio can i do this with the help of react-hot-toast module?

**Comment by leocodeio** [comment]
@karankoder just checked that out guess you can use that, you will not wrap the whole application in a wrapper to achieve this right?
if you are not wrapping up the whole application you can do it using react-hot-toast
ok?

**Comment by leocodeio** [comment]
@karankoder yep!

**Comment by karankoder** [comment]
@leocodeio i have created a PR, please review.

**Comment by leocodeio** [comment]
@karankoder thanks, I will do that

**Comment by leocodeio** [comment]
@karankoder just reviewed, great work thanks for contributing, looking forward to work more with you

**Comment by leocodeio** [comment]
https://www.linkedin.com/in/sai-harsha-vardhan-pittada-8a9a74252/ -- this is my linked In i will share this work in there please do connect in there, thanks
